# .github/workflows/ci.yml
name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write      # Needed to push to ghcr.io

    strategy:
      matrix:
        service: [gateway, events, payments]

    steps:
      - uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          docker build \
            -t ghcr.io/pon4ik7/quickticket-${{ matrix.service }}:${{ github.sha }} \
            ./app/${{ matrix.service }}

      - name: Push image
        run: |
          docker push ghcr.io/pon4ik7/quickticket-${{ matrix.service }}:${{ github.sha }}